const EURO_BOUNDARY_STORAGE="euroBoundaryDebugV1";
const EURO_LABEL_DEBUG_STORAGE="euroLabelDebugV1";
const EURO_BOUNDARY_IMPORTS={};

function boundaryDebugReplacementEntriesForYear(y){return Object.entries(EURO_BOUNDARY_IMPORTS).filter(([,item])=>item.from<=y&&item.to>=y).map(([id,item])=>({id,item}))}
function boundaryDebugRead(){try{return JSON.parse(localStorage.getItem(EURO_BOUNDARY_STORAGE)||"{}")}catch{return{}}}
function boundaryDebugSetStatus(text){const status=dom.boundaryDebugStatus||document.getElementById("boundaryDebugStatus");if(status)status.textContent=text}
function labelDebugRead(){try{return JSON.parse(localStorage.getItem(EURO_LABEL_DEBUG_STORAGE)||"{}")}catch{return{}}}
function labelDebugKey(id,y){return `${id}:${Number(y)||2026}`}
function labelDebugSettings(id,y){const saved=labelDebugRead()[labelDebugKey(id,y)]||{};return{offsetX:Number(saved.offsetX)||0,offsetY:Number(saved.offsetY)||0}}
function labelDebugSetStatus(text){if(dom.labelDebugStatus)dom.labelDebugStatus.textContent=text}

function labelDebugEnsureUi(){
  if(dom.labelDebugTarget||!dom.boundaryDebugDialog)return;
  const section=document.createElement("section");
  section.className="label-debug-section";
  section.innerHTML=`<h3>国名调试</h3><p>仅允许水平／垂直平移，不提供缩放和旋转。调整结果按“实体＋年份”保存。</p><label class="debug-select-label">国名对象<select id="labelDebugTarget" class="debug-select"></select></label><p class="debug-current" id="labelDebugCurrent">当前年份：—</p><div class="debug-grid label-debug-grid"><label>水平平移<input id="labelDebugOffsetX" type="range" min="-240" max="240" step="1" value="0"></label><label>垂直平移<input id="labelDebugOffsetY" type="range" min="-240" max="240" step="1" value="0"></label></div><div class="debug-actions label-debug-actions"><button class="primary-button" id="labelDebugSave" type="button">保存到浏览器</button><button class="text-button" id="labelDebugReset" type="button">恢复默认</button><button class="text-button" id="labelDebugExport" type="button">保存到本地文件</button></div><p class="debug-status" id="labelDebugStatus" role="status"></p>`;
  const anchor=dom.boundaryDebugStatus||dom.boundaryDebugDialog.querySelector("#boundaryDebugStatus");
  if(anchor)anchor.before(section);else dom.boundaryDebugDialog.append(section);
  dom.labelDebugTarget=section.querySelector("#labelDebugTarget");
  dom.labelDebugCurrent=section.querySelector("#labelDebugCurrent");
  dom.labelDebugOffsetX=section.querySelector("#labelDebugOffsetX");
  dom.labelDebugOffsetY=section.querySelector("#labelDebugOffsetY");
  dom.labelDebugSave=section.querySelector("#labelDebugSave");
  dom.labelDebugReset=section.querySelector("#labelDebugReset");
  dom.labelDebugExport=section.querySelector("#labelDebugExport");
  dom.labelDebugStatus=section.querySelector("#labelDebugStatus");
  dom.labelDebugTarget.addEventListener("change",labelDebugLoadValues);
  [dom.labelDebugOffsetX,dom.labelDebugOffsetY].forEach(input=>input.addEventListener("input",()=>{labelDebugUpdateCurrent();createLabels()}));
  dom.labelDebugSave.addEventListener("click",()=>{const all=labelDebugRead();all[labelDebugKey(dom.labelDebugTarget.value,Number(dom.year.value))]={offsetX:Number(dom.labelDebugOffsetX.value)||0,offsetY:Number(dom.labelDebugOffsetY.value)||0};localStorage.setItem(EURO_LABEL_DEBUG_STORAGE,JSON.stringify(all,null,2));createLabels();labelDebugSetStatus("已保存到浏览器。")});
  dom.labelDebugReset.addEventListener("click",()=>{const all=labelDebugRead();delete all[labelDebugKey(dom.labelDebugTarget.value,Number(dom.year.value))];localStorage.setItem(EURO_LABEL_DEBUG_STORAGE,JSON.stringify(all,null,2));labelDebugLoadValues();createLabels();labelDebugSetStatus("已恢复该年份的默认国名位置。")});
  dom.labelDebugExport.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(labelDebugRead(),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="euro-label-debug.json";anchor.click();URL.revokeObjectURL(url);labelDebugSetStatus("已保存国名配置文件。")});
}

function labelDebugUpdateCurrent(){if(!dom.labelDebugCurrent||!dom.labelDebugTarget)return;dom.labelDebugCurrent.textContent=`当前年份：${dom.year.value} · ${formalNameAt(dom.labelDebugTarget.value,Number(dom.year.value))}`}
function labelDebugLoadValues(){if(!dom.labelDebugTarget)return;const saved=labelDebugSettings(dom.labelDebugTarget.value,Number(dom.year.value));dom.labelDebugOffsetX.value=String(saved.offsetX);dom.labelDebugOffsetY.value=String(saved.offsetY);labelDebugUpdateCurrent()}
function updateLabelDebugTargets(){labelDebugEnsureUi();if(!dom.labelDebugTarget)return;const current=dom.labelDebugTarget.value;dom.labelDebugTarget.innerHTML="";const ids=[...new Set(window.EURO_CSHAPES_FEATURES.map(feature=>feature.id))];ids.forEach(id=>{const option=document.createElement("option");option.value=id;option.textContent=formalNameAt(id,Number(dom.year.value));dom.labelDebugTarget.append(option)});if(ids.includes(current))dom.labelDebugTarget.value=current;labelDebugLoadValues()}

function svgPathsFromText(text){const doc=new DOMParser().parseFromString(text,"image/svg+xml");return [...doc.querySelectorAll("path")].map(path=>({d:path.getAttribute("d"),fillRule:path.getAttribute("fill-rule")||"nonzero"})).filter(record=>record.d)}
function boundaryDebugGeoJsonPath(geometry){if(!geometry)return[];const project=([lon,lat])=>[(lon+25)*12,(72-lat)*(650/38)];const ring=coords=>coords.map((point,index)=>{const [x,y]=project(point);return `${index?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`}).join("")+"Z";if(geometry.type==="Polygon")return geometry.coordinates.map(ring).map(d=>({d}));if(geometry.type==="MultiPolygon")return geometry.coordinates.flatMap(polygon=>polygon.map(ring)).map(d=>({d}));return[]}
function boundaryDebugPathFromJson(payload){if(Array.isArray(payload))return payload.filter(item=>typeof item==="string").map(d=>({d}));if(Array.isArray(payload?.paths))return payload.paths.flatMap(item=>typeof item==="string"?[{d:item}]:item?.d?[{d:item.d,fillRule:item.fillRule||"nonzero"}]:[]);if(payload?.type==="Feature"&&payload.geometry)return boundaryDebugGeoJsonPath(payload.geometry);if(payload?.type==="FeatureCollection")return payload.features.flatMap(feature=>boundaryDebugGeoJsonPath(feature.geometry));return[]}
async function boundaryDebugImportFile(){const file=dom.boundaryDebugFile?.files?.[0];const id=dom.boundaryDebugTarget?.value;if(!file||!id){boundaryDebugSetStatus("请选择文件和调试对象。");return}const text=await file.text();let paths=[];try{paths=file.name.toLowerCase().endsWith(".svg")?svgPathsFromText(text):boundaryDebugPathFromJson(JSON.parse(text))}catch{paths=[]}if(!paths.length){boundaryDebugSetStatus("没有读取到可用的 SVG path 或 GeoJSON 几何。");return}EURO_BOUNDARY_IMPORTS[id]={id,from:Number(dom.year.value),to:2026,name:file.name,paths};buildBoundaryMap(Number(dom.year.value));boundaryDebugSetStatus(`已导入 ${file.name}，绑定到 ${formalNameAt(id,Number(dom.year.value))}。`)}
function updateBoundaryDebugTargets(){if(!dom.boundaryDebugTarget)return;labelDebugEnsureUi();updateLabelDebugTargets();const current=dom.boundaryDebugTarget.value;dom.boundaryDebugTarget.innerHTML="";const ids=[...new Set(window.EURO_CSHAPES_FEATURES.map(feature=>feature.id))];ids.forEach(id=>{const option=document.createElement("option");option.value=id;option.textContent=formalNameAt(id,Number(dom.year.value));dom.boundaryDebugTarget.append(option)});if(ids.includes(current))dom.boundaryDebugTarget.value=current;dom.boundaryDebugCurrent.textContent=`当前年份：${dom.year.value} · ${formalNameAt(dom.boundaryDebugTarget.value,Number(dom.year.value))}`}
function initBoundaryDebug(){if(!dom.boundaryDebugButton)return;labelDebugEnsureUi();dom.boundaryDebugButton.addEventListener("click",()=>{updateBoundaryDebugTargets();dom.boundaryDebugDialog.showModal()});dom.boundaryDebugClose.addEventListener("click",()=>dom.boundaryDebugDialog.close());dom.boundaryDebugChooseFile.addEventListener("click",()=>dom.boundaryDebugFile.click());dom.boundaryDebugImport.addEventListener("click",boundaryDebugImportFile);dom.boundaryDebugConfigImportButton.addEventListener("click",()=>dom.boundaryDebugConfigFile.click());dom.boundaryDebugConfigFile.addEventListener("change",async()=>{const file=dom.boundaryDebugConfigFile.files?.[0];if(!file)return;try{Object.assign(EURO_BOUNDARY_IMPORTS,JSON.parse(await file.text()));boundaryDebugSetStatus("已载入调试配置。" )}catch{boundaryDebugSetStatus("调试配置读取失败。")}});dom.boundaryDebugSave.addEventListener("click",()=>{localStorage.setItem(EURO_BOUNDARY_STORAGE,JSON.stringify(EURO_BOUNDARY_IMPORTS,null,2));boundaryDebugSetStatus("已保存到浏览器。")});dom.boundaryDebugReset.addEventListener("click",()=>{Object.keys(EURO_BOUNDARY_IMPORTS).forEach(id=>delete EURO_BOUNDARY_IMPORTS[id]);buildBoundaryMap(Number(dom.year.value));boundaryDebugSetStatus("已恢复数据默认值。")});dom.boundaryDebugExport.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(EURO_BOUNDARY_IMPORTS,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="euro-boundary-debug.json";anchor.click();URL.revokeObjectURL(url)})}
window.boundaryDebugHasReplacementForYear=()=>Object.keys(EURO_BOUNDARY_IMPORTS).length>0;
