const meta={uk:["英国",["英格兰","苏格兰","威尔士"]],ireland:["爱尔兰",["都柏林","科克"]],france:["法国",["巴黎","里昂","马赛"]],spain:["西班牙",["马德里","巴塞罗那","塞维利亚"]],portugal:["葡萄牙",["里斯本","波尔图"]],netherlands:["荷兰",["阿姆斯特丹","鹿特丹"]],belgium:["比利时",["布鲁塞尔","安特卫普"]],germany:["德国",["柏林","汉堡","慕尼黑"]],italy:["意大利",["罗马","米兰","那不勒斯"]],austria:["奥地利",["维也纳","萨尔茨堡"]],czechia:["捷克",["布拉格","布尔诺"]],poland:["波兰",["华沙","克拉科夫"]],romania:["罗马尼亚",["布加勒斯特","雅西"]],hungary:["匈牙利",["布达佩斯","德布勒森"]],bulgaria:["保加利亚",["索非亚","普罗夫迪夫"]],greece:["希腊",["雅典","塞萨洛尼基"]],turkey:["土耳其",["安卡拉","伊斯坦布尔"]],russia:["俄罗斯",["莫斯科","圣彼得堡"]],ukraine:["乌克兰",["基辅","利沃夫"]],finland:["芬兰",["赫尔辛基","图尔库"]],sweden:["瑞典",["斯德哥尔摩","哥德堡"]],norway:["挪威",["奥斯陆","卑尔根"]],denmark:["丹麦",["哥本哈根","奥胡斯"]],switzerland:["瑞士",["伯尔尼","苏黎世"]],germanConfederation:["德意志邦联",["法兰克福","柏林"]],prussia:["普鲁士王国",["柏林","柯尼斯堡"]],austriaEmpire:["奥地利帝国",["维也纳","布达佩斯"]],austriaHungary:["奥匈帝国",["维也纳","布达佩斯"]],germanEmpire:["德意志帝国",["柏林","汉堡"]],piedmont:["撒丁王国",["都灵","热那亚"]],papal:["教皇国",["罗马"]],twoSicilies:["两西西里王国",["那不勒斯","巴勒莫"]],ottoman:["奥斯曼帝国",["伊斯坦布尔","萨洛尼卡"]],czechoslovakia:["捷克斯洛伐克",["布拉格"]],yugoslavia:["南斯拉夫",["贝尔格莱德"]],sovietUnion:["苏联",["莫斯科","列宁格勒"]],sovietRussia:["苏俄",["莫斯科"]],westGermany:["西德",["波恩"]],eastGermany:["东德",["东柏林"]],balkans:["巴尔干历史区域",["贝尔格莱德","索非亚"]]};
const wiki=t=>`https://zh.wikipedia.org/wiki/${encodeURIComponent(t)}`;
const eras=[
  {from:1816,to:1829,title:"维也纳体系下的欧洲",native:"Europa · Europe",badge:"复辟与均势",map:"维也纳体系下的欧洲",summary:"拿破仑战争结束后，欧洲列强以王朝合法性、均势和协商外交维持秩序。德意志邦联、奥地利帝国、普鲁士王国、俄罗斯帝国和奥斯曼帝国构成大陆政治的主要框架。",events:EURO_EVENTS[1816]},
  {from:1830,to:1869,title:"革命、民族主义与统一",native:"Liberty · Nation · Revolution",badge:"民族主义时代",map:"革命与民族国家的形成",summary:"1830年革命、1848年革命和意大利统一运动推动民族国家重组。比利时独立、希腊独立和奥斯曼边疆危机使维也纳体系逐步松动。",events:EURO_EVENTS[1850]},
  {from:1870,to:1913,title:"帝国竞争与工业欧洲",native:"Imperium · Industrie · Nationalstaat",badge:"帝国主义时代",map:"统一国家与帝国竞争",summary:"德意志和意大利统一完成后，欧洲进入工业化、帝国竞争和联盟体系加速发展的阶段。巴尔干成为奥斯曼帝国、俄罗斯、奥匈帝国和列强竞争的交汇点。",events:EURO_EVENTS[1870]},
  {from:1914,to:1918,title:"第一次世界大战与帝国解体",native:"Guerre · Révolution · Rupture",badge:"世界大战",map:"大战与旧帝国的终结",summary:"第一次世界大战摧毁了欧洲旧帝国体系。俄罗斯、奥匈、德意志和奥斯曼帝国相继崩溃，民族自决和革命重新绘制中东欧边界。",events:EURO_EVENTS[1914]},
  {from:1919,to:1938,title:"凡尔赛体系与两种政治",native:"Versailles · Nations · Dictatures",badge:"两次大战之间",map:"凡尔赛体系下的欧洲",summary:"巴黎和会和国际联盟建立了新的国际秩序，但民族少数问题、经济危机和极权政治不断侵蚀战后体系。中东欧出现一批新国家，德国修正主义重新抬头。",events:EURO_EVENTS[1919]},
  {from:1939,to:1945,title:"第二次世界大战",native:"Guerre totale · Europe",badge:"全面战争",map:"第二次世界大战的欧洲",summary:"德国的扩张和同盟体系把欧洲带入第二次世界大战。战争以纳粹德国失败、边界再次移动和欧洲政治中心转向美苏两极而结束。",events:EURO_EVENTS[1939]},
  {from:1946,to:1990,title:"冷战分裂与欧洲一体化",native:"Cold War · Integration",badge:"冷战",map:"铁幕与欧洲一体化",summary:"欧洲被分为美国主导的西方集团和苏联主导的东方集团。与此同时，西欧通过煤钢共同体、罗马条约和后续制度建设推进一体化。",events:EURO_EVENTS[1946]},
  {from:1991,to:2026,title:"后冷战欧洲与安全秩序",native:"Union · Enlargement · War",badge:"当代",map:"后冷战欧洲",summary:"苏联解体和东欧转型带来新的国家体系，欧盟不断扩大，北约东扩；克里米亚危机与俄乌战争又使边界、安全和国家主权问题回到欧洲政治中心。",events:EURO_EVENTS[1991]}
];
const overrides={
  uk:[[1816,2026,"英国","英国在欧洲均势、工业化、帝国扩张和两次世界大战中长期发挥核心作用。","伦敦","君主立宪制"]],france:[[1816,1848,"波旁复辟与七月王朝","法国在复辟、1830年革命和七月王朝之间经历制度转型。","巴黎","君主制"],[1848,1870,"法兰西第二共和国与第二帝国","1848年革命后共和国建立，随后路易-拿破仑建立第二帝国。","巴黎","共和国／帝国"],[1870,1940,"法兰西第三共和国","普法战争后建立的共和国经历殖民扩张、世俗化和两次世界大战。","巴黎","共和国"],[1944,2026,"法兰西共和国","法国在战后重建、欧洲一体化和第五共和国制度下继续发挥欧洲大国作用。","巴黎","共和国"]],germanConfederation:[[1816,1866,"德意志邦联","德意志邦联是维也纳体系下由多个德意志邦国组成的松散政治结构。","法兰克福","邦联"]],prussia:[[1816,1871,"普鲁士王国","普鲁士通过军政改革和对外战争主导德意志统一。","柏林","王国"]],germanEmpire:[[1871,1918,"德意志帝国","统一后的德意志帝国成为欧洲工业、军事和外交强国。","柏林","联邦君主制"]],italy:[[1871,1946,"意大利王国","统一后的意大利王国逐步整合半岛，并在两次世界大战中经历重大转折。","罗马","君主制"],[1946,2026,"意大利共和国","意大利共和国是欧盟与地中海政治的重要成员。","罗马","共和国"]],austriaHungary:[[1867,1918,"奥匈帝国","奥地利与匈牙利通过妥协建立双元帝国，多民族结构最终在一战中解体。","维也纳／布达佩斯","双元君主制"]],ottoman:[[1816,1922,"奥斯曼帝国","奥斯曼帝国在民族主义、列强竞争和改革压力下逐步收缩，最终在一战后解体。","伊斯坦布尔","帝国"]],czechoslovakia:[[1918,1992,"捷克斯洛伐克","一战后建立的多民族共和国，经历纳粹占领、社会主义体制和1989年民主转型。","布拉格","共和国"]],yugoslavia:[[1918,1991,"南斯拉夫","南斯拉夫由战后南斯拉夫王国转为社会主义联邦，最终在民族冲突和政治危机中解体。","贝尔格莱德","王国／联邦共和国"]],sovietUnion:[[1922,1991,"苏联","苏联构成东欧社会主义集团的政治中心，并在1991年解体。","莫斯科","社会主义联邦"]],russia:[[1991,2026,"俄罗斯联邦","俄罗斯联邦继承苏联的主要国际地位，并持续影响欧洲安全结构。","莫斯科","联邦共和国"]],ukraine:[[1991,2026,"乌克兰","乌克兰独立后在欧洲一体化、领土争议和安全危机之间寻找国家方向。","基辅","共和国"]],greece:[[1830,2026,"希腊王国与共和国","希腊独立后经历王政、共和国、军事政权和现代议会民主。","雅典","王国／共和国"]]};
const rulingGroups={uk:[[1816,2026,"英国王室与议会政府"]],france:[[1816,1848,"波旁王室／奥尔良王室"],[1848,1870,"共和派／波拿巴派"],[1870,1940,"共和派联合政府"],[1944,2026,"共和国总统与议会多数"]],germanConfederation:[[1816,1866,"奥地利帝国与邦联成员政府"]],prussia:[[1816,1871,"霍亨索伦王室与普鲁士政府"]],germanEmpire:[[1871,1918,"霍亨索伦王室与帝国政府"]],italy:[[1871,1922,"萨伏依王室与自由派政府"],[1922,1943,"国家法西斯党"],[1946,2026,"议会联盟"]],austriaHungary:[[1867,1918,"哈布斯堡王室与共同政府"]],ottoman:[[1816,1908,"奥斯曼王室与中央政府"],[1908,1918,"青年土耳其党／联合进步委员会"],[1918,1922,"奥斯曼王室与民族运动"]],czechoslovakia:[[1918,1938,"捷克斯洛伐克民主政党联盟"],[1948,1989,"捷克斯洛伐克共产党"],[1989,1992,"公民论坛与民主联盟"]],yugoslavia:[[1918,1941,"塞尔维亚王室"],[1945,1980,"南斯拉夫共产主义者联盟"],[1980,1991,"南斯拉夫联邦轮值与共和国联盟"]],sovietUnion:[[1922,1953,"苏联共产党"],[1953,1991,"苏联共产党"]],russia:[[1991,2026,"总统与联邦政府"]],ukraine:[[1991,2026,"总统与议会联盟"]],greece:[[1830,1967,"王室／议会政党"],[1967,1974,"希腊军政府"],[1974,2026,"新民主党／泛希腊社会主义运动等议会联盟"]]};
const eraFor=y=>eras.find(e=>y>=e.from&&y<=e.to)||eras.at(-1),countryEra=(id,y)=>(overrides[id]||[]).find(([a,b])=>y>=a&&y<=b),polityAt=(id,y)=>{const f=window.EURO_CSHAPES_FEATURES.find(feature=>feature.id===id&&feature.from<=y&&feature.to>=y);return f?.id||id};
const displayNameAt=(id,y)=>window.EURO_META?.[id]?.[0]||meta[id]?.[0]||id;
const formalNameAt=(id,y)=>((window.EURO_FORMAL_NAMES?.[id]||[]).filter(([from,to])=>y>=from&&y<=to).at(-1)||[])[2]||countryEra(id,y)?.[2]||displayNameAt(id,y);
const rulingGroupAt=(id,y)=>(rulingGroups[id]||[]).find(([from,to])=>y>=from&&y<=to)?.[2]||"国家政府与地方政治联盟";
const $=s=>document.querySelector(s),dom={year:$("#yearRange"),yearText:$("#yearText"),play:$("#playButton"),title:$("#mapTitle"),selectedLabel:$("#selectedLabel"),map:$("#menaMap"),schematicRoot:$("#countries"),realRoot:$("#realCountries"),schematicCountries:[...document.querySelectorAll("#countries path")],realCountries:[],labels:$("#labels"),regionLines:$("#regionLines"),frontierOverlays:$("#frontierOverlays"),historyConnectors:$("#historyConnectors"),panelKicker:$("#panelKicker"),polityName:$("#polityName"),polityNative:$("#polityNative"),badge:$("#eraBadge"),facts:$("#facts"),summaryHeading:$("#summaryHeading"),summary:$("#summary"),eventList:$("#eventList"),eventCount:$("#eventCount"),source:$("#boundarySource"),overview:$("#overviewButton"),brand:$("#brandButton"),about:$("#aboutButton"),dialog:$("#aboutDialog"),close:$("#dialogClose"),confirm:$("#dialogConfirm"),jump:$("#jumpButton"),flagDebugButton:$("#flagDebugButton"),flagDebugDialog:$("#flagDebugDialog"),flagDebugClose:$("#flagDebugClose"),flagDebugScaleX:$("#flagDebugScaleX"),flagDebugScaleY:$("#flagDebugScaleY"),flagDebugOffsetX:$("#flagDebugOffsetX"),flagDebugOffsetY:$("#flagDebugOffsetY"),flagDebugRotation:$("#flagDebugRotation"),flagDebugColor:$("#flagDebugColor"),flagDebugSave:$("#flagDebugSave"),flagDebugReset:$("#flagDebugReset"),flagDebugExport:$("#flagDebugExport"),flagDebugStatus:$("#flagDebugStatus"),flagDebugCurrent:$("#flagDebugCurrent"),flagDebugPreview:$("#flagDebugPreview"),boundaryDebugLayer:$("#boundaryDebugLayer"),boundaryDebugButton:$("#boundaryDebugButton"),boundaryDebugDialog:$("#boundaryDebugDialog"),boundaryDebugClose:$("#boundaryDebugClose"),boundaryDebugChooseFile:$("#boundaryDebugChooseFile"),boundaryDebugFile:$("#boundaryDebugFile"),boundaryDebugImport:$("#boundaryDebugImport"),boundaryDebugConfigImportButton:$("#boundaryDebugConfigImportButton"),boundaryDebugConfigFile:$("#boundaryDebugConfigFile"),boundaryDebugTarget:$("#boundaryDebugTarget"),boundaryDebugCurrent:$("#boundaryDebugCurrent"),boundaryDebugScaleX:$("#boundaryDebugScaleX"),boundaryDebugScaleY:$("#boundaryDebugScaleY"),boundaryDebugOffsetX:$("#boundaryDebugOffsetX"),boundaryDebugOffsetY:$("#boundaryDebugOffsetY"),boundaryDebugRotation:$("#boundaryDebugRotation"),boundaryDebugOpacity:$("#boundaryDebugOpacity"),boundaryDebugSave:$("#boundaryDebugSave"),boundaryDebugReset:$("#boundaryDebugReset"),boundaryDebugExport:$("#boundaryDebugExport")};
Object.assign(dom,{mapStage:$("#mapStage"),flagDebugFill:$("#flagDebugFill"),flagLayer:$("#flagLayer")});
let selected=null,activeFlagId=null,timer=null,realMode=false,boundaryKey="";
function eventCards(list){return list.map(([y,n,d,p])=>`<a class="event-card" href="${wiki(p||n)}" target="_blank" rel="noopener noreferrer"><span class="event-year">${y}</span><span><h4>${n}</h4><p>${d}</p></span><span class="event-arrow" aria-hidden="true">↗</span></a>`).join("")}
function render(){const y=Number(dom.year.value),era=eraFor(y),visible=selected?eventsFor(selected,y):era.events;setMapMode(y);dom.yearText.textContent=y;dom.year.style.setProperty("--progress",`${(y-1816)/210*100}%`);if(!selected){dom.selectedLabel.textContent="欧洲总览";dom.panelKicker.textContent=`${y} · REGIONAL OVERVIEW`;dom.polityName.textContent=era.title;dom.polityNative.textContent=era.native;dom.badge.textContent=era.badge;dom.summary.textContent=era.summary;dom.facts.innerHTML=`<div><span>区域格局</span><strong>${era.title}</strong></div><div><span>观察年份</span><strong>${y}</strong></div><div><span>地图状态</span><strong>CShapes-Europe 年度边界</strong></div>`}else{const m=window.EURO_META?.[selected]||meta[selected]||[selected,[]],o=countryEra(selected,y);dom.selectedLabel.textContent=m[0];dom.panelKicker.textContent=`${y} · ${selected.toUpperCase()}`;dom.polityName.textContent=o?.[2]||formalNameAt(selected,y);dom.polityNative.textContent=m[0];dom.badge.textContent=era.badge;dom.summary.textContent=o?.[3]||`${m[0]}在${y}年处于“${era.title}”的历史阶段。`;dom.facts.innerHTML=`<div><span>政治控制</span><strong>${rulingGroupAt(selected,y)}</strong></div><div><span>首府／政治中心</span><strong>${o?.[4]||window.EURO_CSHAPES_FEATURES.find(f=>f.id===selected&&f.from<=y&&f.to>=y)?.capital||"见该年史料"}</strong></div><div><span>政权性质</span><strong>${o?.[5]||"国家或历史政治实体"}</strong></div>`}dom.eventList.innerHTML=eventCards(visible);dom.eventCount.textContent=`${visible.length} 项`;historicalStyles(y);syncFlags(y);document.querySelectorAll(".map-labels text[data-for]").forEach(label=>label.textContent=formalNameAt(label.dataset.for,y));if(dom.flagDebugButton)dom.flagDebugButton.hidden=!selected}
