const EURO_FLAG_DEBUG_STORAGE="euroFlagDebugV1";
const FLAG_COLORS={uk:["#012169","#fff","#c8102e"],ireland:["#169b62","#fff","#ff883e"],france:["#0055a4","#fff","#ef4135"],spain:["#aa151b","#f1bf00","#aa151b"],portugal:["#046a38","#fefefe","#da291c"],netherlands:["#ae1c28","#fff","#21468b"],belgium:["#111","#f1c40f","#e52b2b"],germany:["#111","#d00","#ffce00"],italy:["#009246","#fff","#ce2b37"],austria:["#ed2939","#fff","#ed2939"],poland:["#fff","#fff","#dc143c"],russia:["#fff","#0039a6","#d52b1e"],ukraine:["#0057b7","#ffd700","#ffd700"],greece:["#0d5eaf","#fff","#0d5eaf"],turkey:["#e30a17","#fff","#e30a17"],sweden:["#006aa7","#fecc00","#006aa7"],norway:["#ba0c2f","#fff","#00205b"],denmark:["#c8102e","#fff","#c8102e"],finland:["#fff","#003580","#fff"],default:["#526b9a","#f3d8a0","#526b9a"]};
function flagSvgFor(id){const colors=FLAG_COLORS[id]||FLAG_COLORS.default;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 72"><rect width="120" height="72" fill="${colors[0]}"/><rect y="24" width="120" height="24" fill="${colors[1]}"/><rect y="48" width="120" height="24" fill="${colors[2]}"/><path d="M0 0h120v72H0z" fill="none" stroke="#171411" stroke-width="2"/></svg>`}
function flagAssetFor(id){return{path:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(flagSvgFor(id))}`,period:"CShapes-Europe historical context flag"}}
function readFlagDebug(){try{return JSON.parse(localStorage.getItem(EURO_FLAG_DEBUG_STORAGE)||"{}")}catch{return{}}}
function flagDebugKey(id,y){return `${id}::${y}`}
function flagDebugSettings(id,y){return{scaleX:1,scaleY:1,offsetX:0,offsetY:0,rotation:0,color:stablePolityColor(id),flagFill:stablePolityColor(id),...(readFlagDebug()[flagDebugKey(id,y)]||{})}}
function clearHoverVisuals(){if(dom.flagLayer)dom.flagLayer.innerHTML="";activeFlagId=null;activeCountries().forEach(path=>path.classList.remove("hovered"))}
function setHoverState(id,show){if(!show){if(activeFlagId===id&&!selected)clearHoverVisuals();return}if(selected&&selected!==id)return;clearHoverVisuals();const path=activeCountries().find(candidate=>candidate.dataset.id===id);if(!path)return;activeFlagId=id;path.classList.add("hovered");const box=path.getBBox(),group=document.createElementNS("http://www.w3.org/2000/svg","g"),image=document.createElementNS("http://www.w3.org/2000/svg","image");group.classList.add("country-flag");group.dataset.for=id;image.setAttribute("href",flagAssetFor(id).path);image.setAttribute("x",box.x);image.setAttribute("y",box.y);image.setAttribute("width",box.width);image.setAttribute("height",box.height);image.setAttribute("preserveAspectRatio","xMidYMid slice");group.append(image);dom.flagLayer.append(group)}
function syncFlags(){if(!selected)clearHoverVisuals();else if(!activeFlagId)setHoverState(selected,true)}
function applyFlagDebugSettings(){}
