const POLITY_COLORS={uk:"#315f66",ireland:"#5b8c5a",france:"#526b9a",spain:"#a45d3b",portugal:"#4f755e",netherlands:"#8c5d3d",belgium:"#8d653d",germany:"#5a6477",germanEmpire:"#765c42",prussia:"#3e5a7b",italy:"#5d8064",austria:"#9a713d",austriaEmpire:"#8a6036",austriaHungary:"#936a42",ottoman:"#8b6f47",russia:"#73547e",sovietUnion:"#754f68",sovietRussia:"#76576e",ukraine:"#4e7b88",poland:"#a04e58",czechia:"#617b55",czechoslovakia:"#5e7655",hungary:"#9b6b50",romania:"#7b6a4e",bulgaria:"#607a63",greece:"#6c6387",turkey:"#4b7075",switzerland:"#8b574b",sweden:"#4c6f72",norway:"#5c7d88",denmark:"#8b5d69",finland:"#627b64",yugoslavia:"#6b6d59",westGermany:"#5c6b7c",eastGermany:"#765d73",piedmont:"#687c64",papal:"#82715e",twoSicilies:"#80604f",balkans:"#88674e"};
const HIDDEN_OVERVIEW_LABEL_IDS=new Set(["anhalt","anhaltBernberg","anhaltDessau","hesseHomburg","hesseDarmstadt","saxeAltenburg","saxeCoburgGotha","saxeCoburgSaalfeld","saxeGothaAltenberg","saxeHildburghausen","saxeMeiningen","saxeWeimar","reuss","hohengeroldseck","hohenzollernHechingen","hohenzollernSigmaringen","mecklenburgStrelitz","mecklenburgSchwerin","lucca","massa","cracow","frankfurt","parma","modena","montenegro","oldenburg","saxony","baden","wurttemberg","bosnia-herzegovina","macedonia-fyrom-north-macedonia","kosovo","slovenia"]);
function stablePolityColor(id){return POLITY_COLORS[id]||"#6c6877"}
function activeCountries(){return realMode?dom.realCountries:dom.schematicCountries}
function historicalBoundaryYear(){return true}
function realBoundaryYear(){return true}
function boundaryKeyFor(y){return `cshapes-europe-${y}`}
function clearMapState(){activeFlagId=null;dom.map.setAttribute("viewBox","0 0 1080 650");[...dom.schematicCountries,...dom.realCountries].forEach(p=>p.classList.remove("selected","dimmed","detail-static"));clearHoverVisuals();if(dom.regionLines){dom.regionLines.classList.remove("visible");dom.regionLines.innerHTML=""}if(dom.frontierOverlays)dom.frontierOverlays.innerHTML=""}
function annualFeaturesForYear(y){const byId=new Map();window.EURO_CSHAPES_FEATURES.filter(f=>f.from<=y&&f.to>=y).forEach(f=>{const current=byId.get(f.id),official=f.source?.includes("official"),currentOfficial=current?.source?.includes("official");if(!current||official&&!currentOfficial||official===currentOfficial&&f.from>current.from)byId.set(f.id,f)});return [...byId.values()].filter(f=>f.path)}
function boundaryFeaturesForYear(y){const base=annualFeaturesForYear(y),imports=typeof boundaryDebugReplacementEntriesForYear==="function"?boundaryDebugReplacementEntriesForYear(y):[],ids=new Set(imports.map(entry=>entry.id));return [...base.filter(feature=>!ids.has(feature.id)),...imports.map(({id,item})=>({...item,id,name:window.EURO_META?.[id]?.[0]||meta[id]?.[0]||item.name,source:`导入替换 · ${item.name}`,path:item.paths.map(path=>path.d).join(" ")}))]}
function historicalStyles(y){activeCountries().forEach(path=>{const polity=path.dataset.id,pathColor=stablePolityColor(polity);path.style.setProperty("--polity-color",pathColor);path.dataset.basePolityColor=pathColor;path.classList.remove("dependent","context");const feature=window.EURO_CSHAPES_FEATURES.find(f=>f.id===path.dataset.id&&f.from<=y&&f.to>=y);if(feature?.status&&feature.status!==1)path.classList.add("dependent")})}
function createLabels(){dom.labels.innerHTML="";const seen=new Set(),year=Number(dom.year.value);activeCountries().forEach(p=>{if(seen.has(p.dataset.id)||HIDDEN_OVERVIEW_LABEL_IDS.has(p.dataset.id)||(p.dataset.id==="prussia"&&year>=1871))return;seen.add(p.dataset.id);const box=p.getBBox();if(box.width<18||box.height<15)return;const text=document.createElementNS("http://www.w3.org/2000/svg","text");text.classList.add("country-label");const offset=typeof labelDebugSettings==="function"?labelDebugSettings(p.dataset.id,year):{offsetX:0,offsetY:0};text.setAttribute("x",box.x+box.width/2+offset.offsetX);text.setAttribute("y",box.y+box.height/2+offset.offsetY);text.dataset.for=p.dataset.id;text.textContent=displayNameAt(p.dataset.id,year);dom.labels.append(text)})}
function regions(path){if(!dom.regionLines)return;dom.regionLines.innerHTML="";const box=path.getBBox(),names=window.EURO_META?.[path.dataset.id]?.[1]||meta[path.dataset.id]?.[1]||[];names.slice(0,3).forEach((name,index)=>{const text=document.createElementNS("http://www.w3.org/2000/svg","text");text.setAttribute("x",box.x+box.width*(index%2?.7:.3));text.setAttribute("y",box.y+box.height*(index>1?.75:.3));text.textContent=name;dom.regionLines.append(text)});dom.regionLines.classList.add("visible")}
function choose(id){const path=activeCountries().find(p=>p.dataset.id===id);if(!path)return;selected=id;clearHoverVisuals();const box=path.getBBox(),padX=Math.max(35,box.width*.45),padY=Math.max(30,box.height*.4);dom.map.setAttribute("viewBox",`${box.x-padX} ${box.y-padY} ${box.width+padX*2} ${box.height+padY*2}`);activeCountries().forEach(p=>{const yes=p.dataset.id===id;p.classList.toggle("selected",yes);p.classList.toggle("dimmed",!yes);p.classList.toggle("detail-static",yes)});[...dom.labels.children].forEach(label=>label.style.display=label.dataset.for===id?"none":"");regions(path);requestRender()}
function overview(){selected=null;clearMapState();dom.labels.querySelectorAll("text").forEach(label=>label.style.display="");requestRender()}
function stop(){if(timer)clearInterval(timer);timer=null;dom.play.classList.remove("playing");dom.play.setAttribute("aria-label","播放时间线")}
function toggle(){if(timer)return stop();if(Number(dom.year.value)>=2026)return;dom.play.classList.add("playing");dom.play.setAttribute("aria-label","暂停时间线");timer=setInterval(()=>{const year=Number(dom.year.value);if(year>=2026){stop();return}dom.year.value=year+1;requestRender()},120)}
function bindCountry(path){path.setAttribute("tabindex","0");path.setAttribute("role","button");path.setAttribute("aria-label",`查看${displayNameAt(path.dataset.id,Number(dom.year.value))}`);path.addEventListener("click",()=>choose(path.dataset.id));path.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();choose(path.dataset.id)}});path.addEventListener("mouseenter",()=>setHoverState(path.dataset.id,true));path.addEventListener("mouseleave",()=>{if(!selected)setHoverState(path.dataset.id,false)});path.addEventListener("focus",()=>setHoverState(path.dataset.id,true));path.addEventListener("blur",()=>{if(!selected)setHoverState(path.dataset.id,false)})}
function buildBoundaryMap(y){dom.realRoot.innerHTML="";boundaryFeaturesForYear(y).forEach(feature=>{const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.dataset.id=feature.id;path.dataset.source=feature.source;path.dataset.capital=capitalAt(feature.id,y)||feature.capital||"";path.dataset.status=feature.status||"1";path.setAttribute("d",feature.path);path.setAttribute("fill-rule","evenodd");const title=document.createElementNS("http://www.w3.org/2000/svg","title");title.textContent=`${displayNameAt(feature.id,y)} · ${path.dataset.capital||"首都资料未注明"} · ${feature.source}`;path.append(title);dom.realRoot.append(path)});dom.realCountries=[...dom.realRoot.querySelectorAll("path")];dom.realCountries.forEach(bindCountry);createLabels();historicalStyles(y)}
function setMapMode(y){const key=boundaryKeyFor(y),changed=!realMode||key!==boundaryKey;realMode=true;dom.schematicRoot.style.display="none";dom.realRoot.style.display="";dom.map.classList.add("real-mode");if(changed){selected=null;clearMapState();buildBoundaryMap(y);boundaryKey=key}dom.source.innerHTML=`${y}年边界按 <a href="https://icr.ethz.ch/data/cshapes/" target="_blank" rel="noopener noreferrer">CShapes-Europe</a> 的国家—时期数据模型组织；1816—1885 使用 NASTAC/CShapes-Europe 回溯边界，1886—2019 使用 ETH Zurich CShapes 2.0 正式边界，2020—2026 使用 ETH Zurich CShapes 2.0 正式边界最近一期轮廓；调试器仅用于局部替换。`}
